name: Lint

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test:
    uses: NovaPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '18'
      pkg_manager: 'npm'
      install: 'npm install'
      name: 'test'
      command_one: 'npm run lint'
      command_one_name: 'Lint'
      command_two: 'npm run prettier'
      command_two_name: 'Prettier code.'
      checkout_recursive: false
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
